# ALIASES

alias sublime="open -a /Applications/Sublime\ Text.app"
alias code="open -a Visual\ Studio\ Code.app"
alias ls="exa -la --git --icons --group-directories-first"
alias ll="ls"
alias lsd="exa -laD --git --icons"
alias lst="exa -T --icons --group-directories-first -I=\".git|.history|node_modules\""
alias lstd="exa -DT -I=\".git|.history|node_modules\""
alias rmf="rm -rf"
alias g="git"
alias y="yarn"
alias n="npm"
alias d="docker"
alias dc="docker-compose"
alias cat="bat --paging=never"
alias python="python3"
alias pip="python -m pip"
alias ip="curl icanhazip.com"
alias spot="ncspot"
alias tm="tmux"
alias tms="tmux new -s"
alias tma="tmux attach -t"
alias tmr="tmux rename-session -t"
alias v="nvim"
alias cd="z"
alias find="fd"
alias grep='grep --color'
# alias ..='cd ..'
# alias ...='cd ../..'